apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: freeport.local
spec:
  attachRequired: false      # local/USB storage — no attach/detach controller flow
  podInfoOnMount: false
  volumeLifecycleModes:
    - Persistent
