apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: freeport-manager
  namespace: freeport
spec:
  selector:
    matchLabels:
      name: freeport-manager
  template:
    metadata:
      labels:
        name: freeport-manager
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      terminationGracePeriodSeconds: 5
      hostPID: true
      containers:
      - name: freeport-manager
        image: localhost:32000/freeport-provisioner:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: SYS_CLASS_BLOCK
          value: /sys/class/block
        - name: USB_DEVDIR
          value: /dev/disk/by-id
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: host-dev 
          mountPath: /dev
        - name: host-sys
          mountPath: /sys
        - name: host-proc
          mountPath: /proc
      volumes:
      - name: host-dev 
        hostPath:
          path: /dev
      - name: host-sys
        hostPath:
          path: /sys
      # NOTE: /proc/mounts on host looks different from in container?
      - name: host-proc
        hostPath:
          path: /proc
