FROM golang:1.26-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY pkg pkg
COPY cmd cmd
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o csi-driver ./cmd/node
# RUN CGO_ENABLED=0 go build -o /csi-driver .

FROM alpine:3.21
# mount/umount needed for NodePublishVolume/NodeUnpublishVolume
RUN apk add --no-cache util-linux
COPY --from=builder /src/csi-driver /csi-driver
ENTRYPOINT ["/csi-driver"]
