apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - csicontroller-deployment.yaml
  - csidriver.yaml
  - csinode-daemonset.yaml
  - manager-daemonset.yaml
  - namespace.yaml
  - rbac.yaml
